language: node_js
node_js:
- 9.10.0
cache:
  directories:
  - node_modules
script:
- npm run cypress:run
deploy:
  provider: heroku
  api_key:
    secure: Om8iZIftOOETC5Ea5X7uB3YuWiyVNBwdq9FGcbNoz/ZalZueeBMHHQKIoEuKaDL3DwdAZr7jOmC1C+azzM4/Bnn57kWJOVd1bBjkDGn2BLtWjW0tc7G/b246Qg/DGdRcJkqtUoGIB5N99KXAN/Dw9PB2y4HSDMuJ5M0ga0bx+bux1Sxtby4gpPc/dYypiV3W9aIPCtCfveo4zEnfwclK6U9CaGuSaN3qpJP8Bx5rUCk/5gfFGNQAK4OXlw9Bh+J2GtWiks99/rh/xlx+8jIte5RAY6uJlWp0lUYJzwZbkx0AOFzj7Wx70kwYwoy4+ht0s055Ry/+vT/34HEPdNWFpBGrkXEVxYeJDu1gBxsBkd55MGAQjwGyQ2ZuwrlFOj/wLeRhHB+Fjg2xFCaWC+/oaxngHLeetCJFucW4ZJrbgzHYMi6nD49LH388hN+MEWQgM7RWa+ZZmIjS5yD0LDf/v4RelYhs6d6BOeS03rM5BG16kARjO/1HZVNcn87LdT3DizysOF/QzJ8El76sfyumm+6VRJ2zz61eBp1tGV71SX1V1Cd7pP1QSDIjOed1zypF6EKpRCvXPgyBriiZR65tF9qmUfPefd2FMpRq7oAfi7N6wlug9OfzvJXtIPU4gOijKtZrdY+UA9StF9pCvWEFmNoO+CljCM3fTSdPqyhXEA0=
  app: chips-n-dip